/**
 * Project Intelligence Profiles (Layer 2 completion) — the four-dimension
 * read on a project (investment / lifestyle / financial / market), generated
 * ONCE by AI from the project's REAL stored record and then PERSISTED, so the
 * intelligence settles instead of being re-derived on every question.
 *
 * NOTHING-FAKE rules:
 *  - the profile is AI-generated and labelled as such with its generated_at;
 *  - every fact a dimension cites must be VERBATIM one of the allowed facts
 *    built from the stored record — the server rejects anything else;
 *  - a dimension the stored record cannot support has summary: null plus an
 *    honest note saying what is missing — never a filler paragraph;
 *  - a summary citing zero surviving facts is rejected server-side (nulled);
 *  - AI unreachable / non-JSON ⇒ { ok: false, reason } — never a fake profile.
 *
 * Freshness: facts_hash is a stable hash of the real fields the profile
 * derives from. Stored hash ≠ current hash ⇒ the profile is STALE (the facts
 * changed since generation) — surfaced as a badge, regenerated by the weekly
 * cron or an operator, NEVER silently on read (generation costs an AI call).
 *
 * Persistence idiom mirrors lib/freehold/opportunity.ts (query() + lazy
 * CREATE TABLE IF NOT EXISTS, fail-soft reads).
 */
import { createHash } from 'node:crypto'
import { query } from '@/lib/db'
import { getInventoryPropertyBySlug, getInventoryPropertiesFromDB } from '@/lib/inventory-data'
import { queryServerAgent } from '@/lib/freehold/server-ai'
import type { InventoryProperty } from '@/src/features/freehold-intelligence/inventory'

// ─── Types ───────────────────────────────────────────────────────────────────

export const PROFILE_DIMENSION_KEYS = ['investment', 'lifestyle', 'financial', 'market'] as const
export type ProfileDimensionKey = (typeof PROFILE_DIMENSION_KEYS)[number]

export interface ProfileDimension {
  /** Null when the stored record cannot support this dimension. */
  summary: string | null
  /** Verbatim facts from the stored record backing the summary (subset of the
   *  allowed-facts list — server-enforced). Empty when summary is null. */
  facts: string[]
  /** Present only when summary is null — the honest reason why. */
  note?: string
}

export interface ProjectProfile {
  projectSlug: string
  dimensions: Record<ProfileDimensionKey, ProfileDimension>
  /** Hash of the real fields the profile derived from (staleness anchor). */
  factsHash: string
  generatedAt: string
}

export type GenerateProfileResult =
  | { ok: true; profile: ProjectProfile }
  | { ok: false; reason: string }

export interface ProfileRefreshSummary {
  /** Landing-page projects whose profile is missing or stale. */
  needed: number
  generated: number
  failed: Array<{ slug: string; reason: string }>
  /** Still missing/stale after this bounded run (next cron picks them up). */
  remaining: number
}

// ─── Persistence ─────────────────────────────────────────────────────────────

let ensured: Promise<void> | null = null
async function ensure(): Promise<void> {
  if (!ensured) {
    ensured = (async () => {
      await query(`
        CREATE TABLE IF NOT EXISTS freehold_site_project_profiles (
          project_slug text PRIMARY KEY,
          profile      jsonb,
          facts_hash   text,
          generated_at timestamptz NOT NULL DEFAULT now()
        )`)
    })().catch((e) => { ensured = null; throw e })
  }
  await ensured
}

// ─── Facts (the ONLY material a profile may cite) ────────────────────────────

function fmtAed(n: number): string {
  if (n >= 1_000_000) return `AED ${(n / 1_000_000).toFixed(2).replace(/\.?0+$/, '')}M`
  if (n >= 1_000) return `AED ${Math.round(n / 1_000)}K`
  return `AED ${Math.round(n).toLocaleString()}`
}

/**
 * Stable hash of the real fields the profile derives from. When any of them
 * changes on the project record, the stored profile no longer matches the
 * facts it was generated from ⇒ STALE.
 */
export function factsHash(prop: InventoryProperty): string {
  const basis = {
    name: prop.name,
    price: prop.startingPriceAED,
    maxPrice: prop.maxPriceAED,
    area: prop.area,
    paymentPlan: prop.paymentPlan,
    developer: prop.developer,
    handoverYear: prop.handoverYear,
    roi: prop.roi,
    status: prop.status,
    bedrooms: prop.bedrooms,
    goldenVisa: prop.tags.includes('Golden Visa'),
  }
  return createHash('sha256').update(JSON.stringify(basis)).digest('hex').slice(0, 16)
}

/** The verbatim fact lines a profile is allowed to cite — every one is a real
 *  stored field; an absent field simply never becomes a fact. */
export function buildAllowedFacts(prop: InventoryProperty): string[] {
  const facts: string[] = [`Project: ${prop.name}`]
  if (prop.area) facts.push(`Area: ${prop.area}`)
  if (prop.developer) facts.push(`Developer: ${prop.developer}`)
  if (prop.startingPriceAED && prop.startingPriceAED > 0) facts.push(`Starting price: ${fmtAed(prop.startingPriceAED)}`)
  if (prop.maxPriceAED && prop.maxPriceAED > 0) facts.push(`Price up to: ${fmtAed(prop.maxPriceAED)}`)
  if (prop.paymentPlan) facts.push(`Payment plan: ${prop.paymentPlan}`)
  if (prop.handoverYear) facts.push(`Handover: ${prop.handoverYear}`)
  if (prop.roi != null && prop.roi > 0) facts.push(`Expected rental yield: ${prop.roi}%`)
  facts.push(`Status: ${prop.status.replace(/_/g, ' ')}`)
  if (prop.bedrooms) facts.push(`Unit mix: ${prop.bedrooms}`)
  if (prop.tags.includes('Golden Visa')) facts.push('Golden Visa eligible')
  return facts
}

// ─── Read ────────────────────────────────────────────────────────────────────

type ProfileRow = {
  project_slug: string
  profile: Record<string, unknown> | null
  facts_hash: string | null
  generated_at: string
}

function mapDimension(raw: unknown): ProfileDimension {
  if (!raw || typeof raw !== 'object') {
    return { summary: null, facts: [], note: 'Dimension missing from the stored profile.' }
  }
  const o = raw as Record<string, unknown>
  const summary = typeof o.summary === 'string' && o.summary.trim() ? o.summary.trim() : null
  const facts = Array.isArray(o.facts) ? o.facts.map((f) => String(f)).filter(Boolean) : []
  const note = typeof o.note === 'string' && o.note.trim() ? o.note.trim() : undefined
  return summary ? { summary, facts } : { summary: null, facts: [], ...(note ? { note } : {}) }
}

function mapRow(r: ProfileRow): ProjectProfile {
  const dims = (r.profile && typeof r.profile === 'object'
    ? (r.profile as Record<string, unknown>).dimensions ?? r.profile
    : {}) as Record<string, unknown>
  const dimensions = Object.fromEntries(
    PROFILE_DIMENSION_KEYS.map((k) => [k, mapDimension(dims?.[k])]),
  ) as Record<ProfileDimensionKey, ProfileDimension>
  return {
    projectSlug: r.project_slug,
    dimensions,
    factsHash: r.facts_hash ?? '',
    generatedAt: r.generated_at,
  }
}

/**
 * Read the STORED profile plus a staleness flag (current record hash vs the
 * hash at generation time). NEVER generates — generation costs an AI call and
 * is an explicit act (operator button / weekly cron). Fail-soft: no table, no
 * row or no DB ⇒ { profile: null } so the UI says "not generated yet".
 */
export async function getProjectProfile(
  slug: string,
): Promise<{ profile: ProjectProfile | null; stale: boolean }> {
  try {
    await ensure()
    const rows = await query<ProfileRow>(
      `SELECT project_slug, profile, facts_hash, generated_at
       FROM freehold_site_project_profiles
       WHERE lower(project_slug) = lower($1)
       LIMIT 1`,
      [slug],
    )
    if (!rows[0]) return { profile: null, stale: false }
    const profile = mapRow(rows[0])
    // Stale = the real fields moved since generation. If the project itself
    // can't be loaded right now, we can't judge — report not-stale rather
    // than crying wolf from a transient read failure.
    const prop = await getInventoryPropertyBySlug(slug)
    const stale = prop ? factsHash(prop) !== profile.factsHash : false
    return { profile, stale }
  } catch {
    return { profile: null, stale: false }
  }
}

// ─── Generate ────────────────────────────────────────────────────────────────

const PROFILE_SYSTEM_PROMPT = `You are the project-intelligence analyst for Freehold, a Dubai real estate platform.
You write a four-dimension profile of ONE project using ONLY the stored facts provided. You never invent numbers, amenities, transport links, schools, or market figures. If the stored facts cannot support a dimension, you say so honestly instead of writing filler.
You respond with pure JSON only.`

function buildPrompt(prop: InventoryProperty, allowedFacts: string[]): string {
  return `Write the intelligence profile for this project from its stored record.

STORED RECORD (the complete real data available):
${JSON.stringify(
    {
      name: prop.name,
      slug: prop.slug,
      area: prop.area,
      developer: prop.developer,
      type: prop.type,
      status: prop.status,
      startingPriceAED: prop.startingPriceAED,
      maxPriceAED: prop.maxPriceAED,
      paymentPlan: prop.paymentPlan,
      handoverYear: prop.handoverYear,
      expectedRentalYieldPct: prop.roi,
      unitMix: prop.bedrooms,
      goldenVisaEligible: prop.tags.includes('Golden Visa'),
      tags: prop.tags,
    },
    null,
    2,
  )}

ALLOWED FACTS (the only citations permitted — copy them VERBATIM, character for character):
${allowedFacts.map((f) => `- ${f}`).join('\n')}

Return EXACTLY this JSON shape (no markdown, no extra keys):
{
  "investment": { "summary": string | null, "facts": string[], "note": string | null },
  "lifestyle":  { "summary": string | null, "facts": string[], "note": string | null },
  "financial":  { "summary": string | null, "facts": string[], "note": string | null },
  "market":     { "summary": string | null, "facts": string[], "note": string | null }
}

Dimension angles:
- investment: yield, growth potential, exit — grounded in the stored yield/price/handover facts only.
- lifestyle: family suitability, transport, walkability — the record stores NO transport/school/walkability data, so only write a summary if the stored facts (area, unit mix, status) genuinely support one; otherwise summary null.
- financial: payment flexibility, entry price, investor accessibility — from the stored price/payment plan/Golden Visa facts.
- market: demand, competition, supply — the record stores no market-wide demand/supply figures; only what the stored facts support.

Hard rules:
- "facts" must be a subset of ALLOWED FACTS, copied verbatim. A fact not in the list will be discarded by the server.
- Every summary must be fully supported by the facts it cites — 1 to 3 sentences, no invented numbers, no superlatives the data doesn't earn.
- If a dimension has no real support, set "summary": null, "facts": [], and "note" to one honest sentence naming what data is absent (e.g. "No transport or walkability data is stored for this project.").
- "note" is null whenever "summary" is present.`
}

/** Server-side shape enforcement — the model proposes, the record disposes. */
function sanitizeDimension(raw: unknown, allowed: Set<string>): ProfileDimension {
  if (!raw || typeof raw !== 'object') {
    return { summary: null, facts: [], note: 'The model returned nothing for this dimension.' }
  }
  const o = raw as Record<string, unknown>
  const facts = Array.isArray(o.facts)
    ? [...new Set(o.facts.map((f) => String(f).trim()).filter((f) => allowed.has(f)))]
    : []
  const summary = typeof o.summary === 'string' && o.summary.trim() ? o.summary.trim().slice(0, 600) : null
  const note = typeof o.note === 'string' && o.note.trim() ? o.note.trim().slice(0, 300) : undefined
  if (!summary) {
    return { summary: null, facts: [], note: note ?? 'No supporting data stored for this dimension.' }
  }
  if (facts.length === 0) {
    // NOTHING-FAKE: a summary backed by zero verbatim stored facts is rejected.
    return {
      summary: null,
      facts: [],
      note: 'Rejected: the generated summary cited no fact from this project’s stored record.',
    }
  }
  return { summary, facts }
}

/** Strip an accidental ```json fence and parse, or null. */
function parseJson(raw: string): Record<string, unknown> | null {
  const trimmed = raw.trim().replace(/^```(?:json)?/i, '').replace(/```$/, '').trim()
  try {
    const parsed = JSON.parse(trimmed)
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : null
  } catch {
    return null
  }
}

async function generateFromProp(prop: InventoryProperty): Promise<GenerateProfileResult> {
  const allowedFacts = buildAllowedFacts(prop)
  const allowed = new Set(allowedFacts)

  // Default flash tier — bulk generation surface, no multi-step reasoning.
  // queryServerAgent never throws: with no AI configured it returns the prose
  // offline fallback, which fails JSON parsing below ⇒ honest { ok: false }.
  const raw = await queryServerAgent(buildPrompt(prop, allowedFacts), {
    sessionId: `project-profile:${prop.slug}:${Date.now()}`,
    systemPrompt: PROFILE_SYSTEM_PROMPT,
    responseMimeType: 'application/json',
    temperature: 0.3,
    maxOutputTokens: 1600,
  })
  const parsed = parseJson(raw)
  if (!parsed) {
    return { ok: false, reason: 'AI service unavailable or returned non-JSON — no profile was stored.' }
  }

  const dimensions = Object.fromEntries(
    PROFILE_DIMENSION_KEYS.map((k) => [k, sanitizeDimension(parsed[k], allowed)]),
  ) as Record<ProfileDimensionKey, ProfileDimension>

  // A profile where every dimension came back empty is a generation failure,
  // not intelligence worth persisting over a previous good profile.
  if (PROFILE_DIMENSION_KEYS.every((k) => dimensions[k].summary === null)) {
    return { ok: false, reason: 'Generation produced no dimension supported by the stored record — nothing was stored.' }
  }

  const profile: ProjectProfile = {
    projectSlug: prop.slug,
    dimensions,
    factsHash: factsHash(prop),
    generatedAt: new Date().toISOString(),
  }

  try {
    await ensure()
    await query(
      `INSERT INTO freehold_site_project_profiles (project_slug, profile, facts_hash, generated_at)
       VALUES ($1, $2::jsonb, $3, $4)
       ON CONFLICT (project_slug) DO UPDATE SET
         profile = EXCLUDED.profile,
         facts_hash = EXCLUDED.facts_hash,
         generated_at = EXCLUDED.generated_at`,
      [profile.projectSlug, JSON.stringify({ dimensions: profile.dimensions }), profile.factsHash, profile.generatedAt],
    )
  } catch (err) {
    return { ok: false, reason: err instanceof Error ? err.message : 'Could not persist the profile.' }
  }
  return { ok: true, profile }
}

/**
 * Generate (or regenerate) the profile for one project from its full real
 * record and persist it with the facts hash + timestamp. Explicit-only — the
 * operator button, the weekly cron; never called from a read path.
 */
export async function generateProjectProfile(slug: string): Promise<GenerateProfileResult> {
  const prop = await getInventoryPropertyBySlug(slug)
  if (!prop) return { ok: false, reason: `No project "${slug}" in the catalog.` }
  return generateFromProp(prop)
}

/**
 * Weekly freshness pass: regenerate ONLY profiles that are missing or stale
 * (facts hash mismatch) for projects that have a landing page, capped per run
 * so AI spend stays bounded. Returns an honest remaining count — the next run
 * continues where this one stopped.
 */
export async function refreshStaleProjectProfiles(cap = 25): Promise<ProfileRefreshSummary> {
  const props = await getInventoryPropertiesFromDB()
  // "Has a landing page" = a landing page row exists (published or draft).
  const withLanding = props.filter((p) => p.landingSlug)

  let storedHashes = new Map<string, string>()
  try {
    await ensure()
    const rows = await query<{ project_slug: string; facts_hash: string | null }>(
      `SELECT project_slug, facts_hash FROM freehold_site_project_profiles`,
    )
    storedHashes = new Map(rows.map((r) => [r.project_slug.toLowerCase(), r.facts_hash ?? '']))
  } catch {
    // Table unreadable — treat everything as missing; generation re-ensures.
  }

  const needs = withLanding.filter((p) => storedHashes.get(p.slug.toLowerCase()) !== factsHash(p))
  const batch = needs.slice(0, Math.max(0, cap))
  const failed: Array<{ slug: string; reason: string }> = []
  let generated = 0
  // Sequential on purpose — a bounded, gentle pass, not a burst of AI calls.
  for (const prop of batch) {
    const result = await generateFromProp(prop)
    if (result.ok) generated += 1
    else failed.push({ slug: prop.slug, reason: result.reason })
  }
  return {
    needed: needs.length,
    generated,
    failed,
    remaining: needs.length - generated,
  }
}
