"use client"

import { useState } from "react"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"
import { Badge } from "@/components/ui/badge"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Database, FileCheck, History, Info } from "lucide-react"

interface EvidenceDrawerProps {
  requestId?: string
  sources?: string[]
  runId?: string
  timestamp?: string
  children: React.ReactNode
}

export function EvidenceDrawer({ requestId, sources = [], runId, timestamp, children }: EvidenceDrawerProps) {
  return (
    <Sheet>
      <SheetTrigger asChild>
        {children}
      </SheetTrigger>
      <SheetContent side="right" className="w-[400px] sm:w-[540px]">
        <SheetHeader className="border-b pb-4">
          <div className="flex items-center gap-2 mb-2">
            <Database className="h-5 w-5 text-primary" />
            <SheetTitle className="font-serif text-2xl">Evidence Drawer</SheetTitle>
          </div>
          <SheetDescription>
            Audit trail and source verification for this intelligence response.
          </SheetDescription>
        </SheetHeader>
        
        <ScrollArea className="h-[calc(100vh-180px)] mt-6 pr-4">
          <div className="space-y-8">
            {/* Run Provenance */}
            <section>
              <div className="flex items-center gap-2 mb-3 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                <History className="h-4 w-4" /> Provenance
              </div>
              <div className="rounded-lg border bg-muted/30 p-4 space-y-3">
                <div className="flex justify-between items-center text-xs">
                  <span className="text-muted-foreground">Run ID</span>
                  <code className="bg-background px-1.5 py-0.5 rounded border">{runId || "run_20260322_001"}</code>
                </div>
                <div className="flex justify-between items-center text-xs">
                  <span className="text-muted-foreground">Request ID</span>
                  <code className="bg-background px-1.5 py-0.5 rounded border">{requestId || "req_5592_ax"}</code>
                </div>
                <div className="flex justify-between items-center text-xs">
                  <span className="text-muted-foreground">Snapshot TS</span>
                  <span className="font-medium">{timestamp || "2026-03-22 13:25 UTC"}</span>
                </div>
              </div>
            </section>

            {/* Sources Used */}
            <section>
              <div className="flex items-center gap-2 mb-3 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                <FileCheck className="h-4 w-4" /> Data Sources
              </div>
              <div className="space-y-2">
                {(sources.length > 0 ? sources : ["gc_projects", "gc_market_scores_v1", "pf_listings_aggregated"]).map((source) => (
                  <div key={source} className="flex items-center gap-2 p-3 rounded-md bg-card border text-sm">
                    <div className="h-2 w-2 rounded-full bg-green-500" />
                    <span className="font-mono text-xs">{source}</span>
                    <Badge variant="outline" className="ml-auto text-[10px]">Verified</Badge>
                  </div>
                ))}
              </div>
            </section>

            {/* Confidence Explanation */}
            <section>
              <div className="flex items-center gap-2 mb-3 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                <Info className="h-4 w-4" /> Methodology
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                This response was generated by the Ask Compiler (v1.6.2) using a weighted analysis of current market listings, 
                historical absorption rates, and developer trust indices. 
                <br /><br />
                <span className="font-bold text-foreground italic">&ldquo;Investment intelligence is descriptive, not predictive.&rdquo;</span>
              </p>
            </section>
          </div>
        </ScrollArea>

        <div className="absolute bottom-6 left-6 right-6 pt-4 border-t text-[10px] text-muted-foreground text-center">
          Entrestate Intelligence OS — Enterprise Tier Data Contract Applied
        </div>
      </SheetContent>
    </Sheet>
  )
}
