import type { TargetingTemplate } from './types'

export const TARGETING_TEMPLATES: TargetingTemplate[] = [
  {
    id:             'tmpl_uae_investor',
    name:           'UAE Premium Investor',
    description:    'High-net-worth UAE residents actively researching off-plan and ready investment property. Targets key investor corridors — Dubai + Abu Dhabi.',
    audience:       'UAE residents, 30–60, high-value property interests',
    estimatedReach: '45,000 – 80,000',
    useCase:        'investor',
    targeting: {
      countries:          ['AE'],
      cityKeys:           ['2562407', '2563573'],
      ageMin:             30,
      ageMax:             60,
      publisherPlatforms: ['facebook', 'instagram'],
      interests: [
        { id: '6003051380892', name: 'Real estate investing'  },
        { id: '6003232090805', name: 'Property investment'    },
        { id: '6003393547471', name: 'Luxury real estate'     },
      ],
    },
  },
  {
    id:             'tmpl_uae_end_user',
    name:           'UAE Family End User',
    description:    'Families looking for primary residences in quality suburban neighbourhoods. School districts and community-living signals.',
    audience:       'UAE residents, 28–50, family & homeownership interests',
    estimatedReach: '90,000 – 160,000',
    useCase:        'end_user',
    targeting: {
      countries:          ['AE'],
      cityKeys:           ['2562407', '2565040', '2559677'],
      ageMin:             28,
      ageMax:             50,
      publisherPlatforms: ['facebook', 'instagram'],
      interests: [
        { id: '6003016230512', name: 'Home improvement'       },
        { id: '6003031641196', name: 'Family'                  },
        { id: '6002980726932', name: 'First-time home buyer'  },
      ],
    },
  },
  {
    id:             'tmpl_golden_visa',
    name:           'Golden Visa Seekers',
    description:    'High-income expats and international residents researching UAE residency through property. AED 2M+ budget signal. Dubai-first.',
    audience:       'UAE + GCC expats, 28–55, residency & investment interests',
    estimatedReach: '30,000 – 55,000',
    useCase:        'golden_visa',
    targeting: {
      countries:          ['AE'],
      cityKeys:           ['2562407'],
      ageMin:             28,
      ageMax:             55,
      publisherPlatforms: ['facebook', 'instagram'],
      interests: [
        { id: '6003051380892', name: 'Real estate investing'  },
        { id: '6003393547471', name: 'Luxury real estate'     },
        { id: '6003232090805', name: 'Property investment'    },
        { id: '6003016230512', name: 'UAE residency'          },
      ],
    },
  },
  {
    id:             'tmpl_international',
    name:           'International Investor',
    description:    'GCC and international buyers comparing Dubai against other global markets. Suitable for flagship, beachfront, and high-ticket projects.',
    audience:       'GCC + Europe + Asia, 32–65, luxury property interests',
    estimatedReach: '200,000 – 400,000',
    useCase:        'international',
    targeting: {
      countries:          ['AE', 'SA', 'KW', 'QA', 'BH', 'OM', 'GB', 'DE', 'IN'],
      cityKeys:           [],
      ageMin:             32,
      ageMax:             65,
      publisherPlatforms: ['facebook', 'instagram'],
      interests: [
        { id: '6003393547471', name: 'Luxury real estate'     },
        { id: '6003051380892', name: 'Real estate investing'  },
      ],
    },
  },
  {
    id:             'tmpl_secondary',
    name:           'Secondary Market Buyer',
    description:    'Buyers comparing resale and secondary market options. Lower entry, faster handover, and rental yield are their key signals.',
    audience:       'UAE residents, 28–55, secondary market interests',
    estimatedReach: '60,000 – 100,000',
    useCase:        'secondary',
    targeting: {
      countries:          ['AE'],
      cityKeys:           ['2562407', '2563573'],
      ageMin:             28,
      ageMax:             55,
      publisherPlatforms: ['facebook', 'instagram'],
      interests: [
        { id: '6003232090805', name: 'Property investment'    },
        { id: '6003016230512', name: 'Real estate'            },
        { id: '6003031641196', name: 'Rental properties'      },
      ],
    },
  },
]
