/**
 * Generate the canonical list of REAL app routes.
 *
 * Why this exists: the Expert chat can emit a link to anywhere. The link
 * sanitizer used to allow any path that merely *looked* static, so a wholly
 * invented path like
 *   /freehold-intelligence/library/creatives/edit/generated_image_x.png
 * passed straight through and 404'd — the "every link from the AI is 404"
 * report. Verifying a record id is not enough; the ROUTE itself has to exist.
 *
 * Run by `pnpm guards` (and directly via `pnpm routes`). Writes
 * lib/freehold/app-routes.generated.ts.
 */
import { readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

const APP_DIR = 'app'
const OUT = 'lib/freehold/app-routes.generated.ts'

/** Every directory holding a page.tsx becomes a route. */
function collectPageDirs(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (!statSync(full).isDirectory()) continue
    if (existsSync(join(full, 'page.tsx')) || existsSync(join(full, 'page.ts'))) acc.push(full)
    collectPageDirs(full, acc)
  }
  return acc
}

/**
 * app/(marketing)/about/page.tsx      → /about
 * app/lp/[slug]/page.tsx              → /lp/:param
 * app/blog/[...rest]/page.tsx         → /blog/:rest   (catch-all)
 */
function toRoutePattern(dirPath: string): string {
  const rel = relative(APP_DIR, dirPath).split(sep)
  const segs: string[] = []
  for (const s of rel) {
    if (s.startsWith('(') && s.endsWith(')')) continue // route group — not in the URL
    if (s.startsWith('@')) continue                    // parallel route slot
    if (/^\[\[?\.\.\./.test(s)) { segs.push('**'); continue } // [...x] / [[...x]]
    if (s.startsWith('[') && s.endsWith(']')) { segs.push('*'); continue }
    segs.push(s)
  }
  return '/' + segs.join('/')
}

const routes = Array.from(
  new Set(
    collectPageDirs(APP_DIR)
      .map(toRoutePattern)
      // API handlers are not navigable pages.
      .filter((r) => !r.startsWith('/api')),
  ),
).sort()
// The app root itself.
if (existsSync(join(APP_DIR, 'page.tsx'))) routes.unshift('/')

const banner = `// GENERATED by scripts/gen-app-routes.ts — do not edit by hand.
// Every navigable route in the app. '*' = one dynamic segment, '**' = catch-all.
// Used by the Expert chat's link sanitizer so it can never hand out a path
// that does not exist.
`
const body = `${banner}export const APP_ROUTES: readonly string[] = ${JSON.stringify(routes, null, 2)} as const\n`

const prev = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
if (prev !== body) {
  writeFileSync(OUT, body)
  console.log(`[routes] wrote ${routes.length} routes → ${OUT}`)
} else {
  console.log(`[routes] up to date (${routes.length} routes)`)
}
