'use client'

import { useState } from 'react'
import { CheckCircle, Lock, ChevronDown, ChevronUp, Shield } from 'lucide-react'

type Permission =
  | 'view_campaigns'
  | 'create_campaigns'
  | 'manage_budget'
  | 'view_attribution'
  | 'manage_landings'
  | 'manage_creatives'
  | 'view_leads'
  | 'export_leads'
  | 'manage_requirements'
  | 'view_competitor'

type AgentPerms = {
  id: string
  name: string
  initials: string
  tier: string
  perms: Record<Permission, boolean>
}

const PERM_GROUPS: { label: string; items: { id: Permission; label: string; desc: string }[] }[] = [
  {
    label: 'Campaigns',
    items: [
      { id: 'view_campaigns',   label: 'View campaigns',    desc: 'See running and paused campaigns' },
      { id: 'create_campaigns', label: 'Create campaigns',  desc: 'Launch new ad campaigns (charges wallet)' },
      { id: 'manage_budget',    label: 'Manage budget',     desc: 'Adjust spend and bid settings' },
    ],
  },
  {
    label: 'Attribution & Reporting',
    items: [
      { id: 'view_attribution', label: 'View attribution',  desc: 'See which campaigns generated which leads' },
    ],
  },
  {
    label: 'Assets',
    items: [
      { id: 'manage_landings',  label: 'Manage landings',   desc: 'Edit and publish landing pages' },
      { id: 'manage_creatives', label: 'Manage creatives',  desc: 'Upload and edit ad creatives' },
    ],
  },
  {
    label: 'Leads',
    items: [
      { id: 'view_leads',       label: 'View leads',        desc: 'See leads generated by their campaigns' },
      { id: 'export_leads',     label: 'Export leads',      desc: 'Download lead data as CSV' },
    ],
  },
  {
    label: 'Settings',
    items: [
      { id: 'manage_requirements', label: 'Edit requirements', desc: 'Change targeting and lead requirements' },
      { id: 'view_competitor',     label: 'Competitor data',   desc: 'View competitive ad analysis' },
    ],
  },
]

const DEFAULT_GOLD: Record<Permission, boolean> = {
  view_campaigns: true, create_campaigns: true,  manage_budget: true,
  view_attribution: true, manage_landings: true, manage_creatives: true,
  view_leads: true, export_leads: true, manage_requirements: false, view_competitor: false,
}
const DEFAULT_SILVER: Record<Permission, boolean> = {
  view_campaigns: true, create_campaigns: true,  manage_budget: false,
  view_attribution: true, manage_landings: false, manage_creatives: true,
  view_leads: true, export_leads: false, manage_requirements: false, view_competitor: false,
}
const DEFAULT_BRONZE: Record<Permission, boolean> = {
  view_campaigns: true, create_campaigns: false, manage_budget: false,
  view_attribution: false, manage_landings: false, manage_creatives: false,
  view_leads: true, export_leads: false, manage_requirements: false, view_competitor: false,
}

const INITIAL_AGENTS: AgentPerms[] = [
  { id: 'a1', name: 'Noura Al Hassan', initials: 'NA', tier: 'Gold',   perms: { ...DEFAULT_GOLD   } },
  { id: 'a2', name: 'James Cooper',    initials: 'JC', tier: 'Silver', perms: { ...DEFAULT_SILVER } },
  { id: 'a3', name: 'Priya Sharma',    initials: 'PS', tier: 'Bronze', perms: { ...DEFAULT_BRONZE } },
  { id: 'a4', name: 'Omar Khalil',     initials: 'OK', tier: 'Silver', perms: { ...DEFAULT_SILVER } },
]

const TIER_COLOR: Record<string, string> = {
  Bronze:   'text-orange-400 border-orange-400/25 bg-orange-400/10',
  Silver:   'text-white/65   border-white/15      bg-white/[0.06]',
  Gold:     'text-[#D4AF37]  border-[#D4AF37]/25  bg-[#D4AF37]/10',
  Platinum: 'text-violet-300 border-violet-400/25 bg-violet-400/10',
}

export default function PermissionsPage() {
  const [agents, setAgents]     = useState<AgentPerms[]>(INITIAL_AGENTS)
  const [expanded, setExpanded] = useState<string>(INITIAL_AGENTS[0].id)
  const [saved, setSaved]       = useState<string[]>([])

  function toggle(agentId: string, perm: Permission) {
    setAgents((prev) =>
      prev.map((a) =>
        a.id === agentId ? { ...a, perms: { ...a.perms, [perm]: !a.perms[perm] } } : a,
      ),
    )
  }

  function saveAgent(agentId: string) {
    setSaved((prev) => [...prev, agentId])
    setTimeout(() => setSaved((prev) => prev.filter((x) => x !== agentId)), 2000)
  }

  return (
    <div className="mx-auto max-w-3xl px-5 pb-20 pt-7 sm:px-8">

      {/* Header */}
      <div className="mb-8">
        <h1 className="text-[20px] font-semibold text-white">Team Permissions</h1>
        <p className="mt-1 text-[13px] text-white/35">
          Control what each agent can see and do inside Lead Machine. Changes take effect immediately.
        </p>
      </div>

      {/* Agent list */}
      <div className="space-y-3">
        {agents.map((agent) => {
          const tc = TIER_COLOR[agent.tier] ?? TIER_COLOR.Bronze
          const isOpen = expanded === agent.id
          const permCount = Object.values(agent.perms).filter(Boolean).length
          const isSaved = saved.includes(agent.id)

          return (
            <div
              key={agent.id}
              className={`rounded-[20px] border bg-[#131B2B] transition ${isOpen ? 'border-white/15' : 'border-white/[0.07]'}`}
            >
              {/* Agent row */}
              <button
                className="flex w-full items-center gap-4 px-5 py-4 text-left"
                onClick={() => setExpanded(isOpen ? '' : agent.id)}
              >
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#D4AF37]/15 text-[13px] font-bold text-[#D4AF37]">
                  {agent.initials}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-[14px] font-semibold text-white">{agent.name}</div>
                  <div className="mt-0.5 flex items-center gap-2">
                    <span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${tc}`}>
                      {agent.tier}
                    </span>
                    <span className="text-[11px] text-white/25">{permCount} permissions active</span>
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  {isSaved && <CheckCircle className="h-4 w-4 text-emerald-400" />}
                  {isOpen ? <ChevronUp className="h-4 w-4 text-white/25" /> : <ChevronDown className="h-4 w-4 text-white/25" />}
                </div>
              </button>

              {/* Permission groups */}
              {isOpen && (
                <div className="border-t border-white/[0.06] px-5 pb-5 pt-4">
                  <div className="space-y-5">
                    {PERM_GROUPS.map((group) => (
                      <div key={group.label}>
                        <div className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-white/25">
                          {group.label}
                        </div>
                        <div className="space-y-2">
                          {group.items.map((item) => {
                            const on = agent.perms[item.id]
                            return (
                              <label
                                key={item.id}
                                className="flex cursor-pointer items-center gap-3 rounded-[12px] border border-white/[0.05] bg-white/[0.02] px-4 py-3 transition hover:border-white/10"
                              >
                                <input
                                  type="checkbox"
                                  checked={on}
                                  onChange={() => toggle(agent.id, item.id)}
                                  className="sr-only"
                                />
                                <div className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-md border transition ${
                                  on ? 'border-[#D4AF37]/60 bg-[#D4AF37]/20' : 'border-white/[0.10] bg-transparent'
                                }`}>
                                  {on ? (
                                    <CheckCircle className="h-3.5 w-3.5 text-[#D4AF37]" />
                                  ) : (
                                    <Lock className="h-3 w-3 text-white/20" />
                                  )}
                                </div>
                                <div className="flex-1 min-w-0">
                                  <div className={`text-[13px] font-medium ${on ? 'text-white/85' : 'text-white/35'}`}>
                                    {item.label}
                                  </div>
                                  <div className="text-[11px] text-white/25">{item.desc}</div>
                                </div>
                              </label>
                            )
                          })}
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="mt-5 flex items-center gap-2">
                    <button
                      onClick={() => saveAgent(agent.id)}
                      className="flex items-center gap-1.5 rounded-full bg-[#D4AF37] px-4 py-2 text-[12px] font-semibold text-black transition hover:bg-[#D4AF37]/90"
                    >
                      <Shield className="h-3.5 w-3.5" />
                      Save permissions
                    </button>
                    <button
                      onClick={() => setExpanded('')}
                      className="rounded-full border border-white/[0.08] px-4 py-2 text-[12px] text-white/35 transition hover:text-white/60"
                    >
                      Close
                    </button>
                  </div>
                </div>
              )}
            </div>
          )
        })}
      </div>

    </div>
  )
}
